
import { TranslationSet, Language } from './types';

export const TRANSLATIONS: Record<Language, TranslationSet> = {
  en: {
    title: 'Hayat',
    tagline: 'Smart Emergency Triage System for Moroccan Hospitals',
    hero_title: 'Hayat',
    hero_subtitle: 'Intelligent Triage. Faster Care. Lives Saved. Reducing emergency wait times by 30-40% in Moroccan CHUs.',
    get_started: 'Launch Live Demo',
    learn_more: 'View Methodology',
    intake: 'Patient Admission',
    queue: 'Real-time Triage Queue',
    analytics: 'Predictive Flow Analytics',
    patient_name: 'Patient Name',
    age: 'Age',
    vitals: 'Vital Signs',
    hr: 'Heart Rate',
    bp: 'Blood Pressure',
    spo2: 'SpO2 %',
    temp: 'Temp °C',
    symptoms: 'Clinical Symptoms',
    submit: 'Run AI Triage',
    waiting: 'Active Cases',
    priority_p1: 'P1 - Immediate',
    priority_p2: 'P2 - Very Urgent',
    priority_p3: 'P3 - Urgent',
    priority_p4: 'P4 - Standard',
    priority_p5: 'P5 - Non-urgent',
    explanation: 'SHAP Explainability',
    impact_title: 'Objective Impact Metrics',
    wait_time_reduction: '30-40% Wait Reduction',
    critical_detection: '98.4% Critical Detection',
    burnout_reduction: '30% Staff Relief',
    data_driven_title: 'Trained on 40K+ MIMIC-IV Records',
    data_driven_desc: 'Leveraging XGBoost for classification and LSTM for flow forecasting.',
    dashboard: {
      header: 'Clinical Operations Dashboard',
      subHeader: 'Real-time emergency unit telemetry • Moroccan CHU Pilot',
      admission: 'Admission',
      activeMatrix: 'Active Triage Matrix',
      forecastTitle: 'LSTM Arrival Forecast',
      forecastSub: 'Next 24 Hours Prediction',
      aiCopilot: 'AI Copilot Insights',
      unitHealth: 'Unit Health Matrix',
      stats: {
        waiting: 'Patients Waiting',
        critical: 'Critical Cases',
        avgWait: 'Avg Wait (min)',
        utilization: 'Staff Utilization'
      }
    },
    patientDetail: {
      waitTime: 'Wait Time',
      riskScore: 'Risk Score',
      shapTitle: 'SHAP Priority Justification',
      vitalsTitle: 'Patient Vitals',
      resourceTitle: 'Resource Status',
      assignPhysician: 'Assign Physician',
      updatePriority: 'Update Priority'
    },
    auth: {
      signIn: 'Sign In',
      signUp: 'Sign Up',
      signOut: 'Sign Out',
      email: 'Email Address',
      password: 'Password',
      fullName: 'Full Name',
      role: 'Role',
      hospital: 'Hospital / CHU',
      noAccount: "Don't have an account?",
      haveAccount: 'Already have an account?',
      rememberMe: 'Remember me',
      forgotPassword: 'Forgot password?',
    },
    saas: {
      pricing: 'Pricing & Plans',
      billing: 'Billing',
      adminPanel: 'Admin Super-Dashboard',
      apiDocs: 'API Documentation',
      hospitalSwitcher: 'Switch Hospital',
      upgradePlan: 'Upgrade Plan',
    },
  },
  fr: {
    title: 'Hayat',
    tagline: 'Système de Tri Intelligent des Urgences pour les Hôpitaux Marocains',
    hero_title: 'Hayat',
    hero_subtitle: 'Triage Intelligent. Soins Rapides. Vies Sauvées. Réduction des temps d’attente de 30-40%.',
    get_started: 'Démo en Direct',
    learn_more: 'Méthodologie',
    intake: 'Admission Patient',
    queue: 'File de Tri Temps Réel',
    analytics: 'Analyses Prédictives',
    patient_name: 'Nom du Patient',
    age: 'Âge',
    vitals: 'Signes Vitaux',
    hr: 'Freq. Cardiaque',
    bp: 'Tension',
    spo2: 'SpO2 %',
    temp: 'Temp °C',
    symptoms: 'Symptômes',
    submit: 'Lancer le Tri IA',
    waiting: 'Cas Actifs',
    priority_p1: 'P1 - Immédiat',
    priority_p2: 'P2 - Très Urgent',
    priority_p3: 'P3 - Urgent',
    priority_p4: 'P4 - Standard',
    priority_p5: 'P5 - Non-urgent',
    explanation: 'Explicabilité SHAP',
    impact_title: 'Mesures d’Impact',
    wait_time_reduction: '40% d’Attente en Moins',
    critical_detection: '98.4% de Détection',
    burnout_reduction: '30% d’Efficacité Staff',
    data_driven_title: 'Basé sur 40K+ Dossiers MIMIC-IV',
    data_driven_desc: 'Utilisation de XGBoost pour le tri et LSTM pour la prévision.',
    dashboard: {
      header: 'Tableau des Opérations Cliniques',
      subHeader: 'Télémétrie des urgences en temps réel • Pilote CHU Maroc',
      admission: 'Admission',
      activeMatrix: 'Matrice de Triage Active',
      forecastTitle: 'Prévision d’Arrivées LSTM',
      forecastSub: 'Prédiction sur les prochaines 24 heures',
      aiCopilot: 'Aperçus Copilote IA',
      unitHealth: 'Matrice de Santé de l’Unité',
      stats: {
        waiting: 'Patients en Attente',
        critical: 'Cas Critiques',
        avgWait: 'Attente Moy. (min)',
        utilization: 'Utilisation du Staff'
      }
    },
    patientDetail: {
      waitTime: 'Temps d’Attente',
      riskScore: 'Score de Risque',
      shapTitle: 'Justification de Priorité SHAP',
      vitalsTitle: 'Signes Vitaux du Patient',
      resourceTitle: 'Statut des Ressources',
      assignPhysician: 'Assigner Médecin',
      updatePriority: 'Modifier Priorité'
    },
    auth: {
      signIn: 'Se Connecter',
      signUp: "S'Inscrire",
      signOut: 'Déconnexion',
      email: 'Adresse Email',
      password: 'Mot de passe',
      fullName: 'Nom Complet',
      role: 'Rôle',
      hospital: 'Hôpital / CHU',
      noAccount: "Pas de compte ?",
      haveAccount: 'Déjà inscrit ?',
      rememberMe: 'Se souvenir de moi',
      forgotPassword: 'Mot de passe oublié ?',
    },
    saas: {
      pricing: 'Tarifs et Plans',
      billing: 'Facturation',
      adminPanel: 'Tableau Super-Admin',
      apiDocs: 'Documentation API',
      hospitalSwitcher: 'Changer d’Hôpital',
      upgradePlan: 'Améliorer mon Plan',
    },
  },
  ar: {
    title: 'حياة',
    tagline: 'نظام فرز الطوارئ الذكي للمستشفيات المغربية',
    hero_title: 'حياة',
    hero_subtitle: 'فرز ذكي. رعاية أسرع. إنقاذ الأرواح. تقليل وقت الانتظار بنسبة 30-40%.',
    get_started: 'تشغيل العرض المباشر',
    learn_more: 'المنهجية العلمية',
    intake: 'استقبال المريض',
    queue: 'قائمة الفرز المباشر',
    analytics: 'التحليلات التنبؤية',
    patient_name: 'اسم المريض',
    age: 'السن',
    vitals: 'العلامات الحيوية',
    hr: 'النبض',
    bp: 'ضغط الدم',
    spo2: 'الأكسجين %',
    temp: 'الحرارة',
    symptoms: 'الأعراض',
    submit: 'تحليل الذكاء الاصطناعي',
    waiting: 'الحالات النشطة',
    priority_p1: 'P1 - فوري',
    priority_p2: 'P2 - عاجل جداً',
    priority_p3: 'P3 - عاجل',
    priority_p4: 'P4 - عادي',
    priority_p5: 'P5 - غير عاجل',
    explanation: 'تفسير SHAP',
    impact_title: 'مقاييس التأثير',
    wait_time_reduction: 'خفض الانتظار بنسبة 40%',
    critical_detection: '98% دقة الاكتشاف',
    burnout_reduction: '30% تخفيف الضغط',
    data_driven_title: 'مدرب على 40 ألف سجل طبي',
    data_driven_desc: 'استخدام نماذج XGBoost و LSTM لتحسين الموارد.',
    dashboard: {
      header: 'لوحة العمليات السريرية',
      subHeader: 'قياسات وحدة الطوارئ في الوقت الفعلي • مشروع CHU المغربي',
      admission: 'استقبال',
      activeMatrix: 'مصفوفة الفرز النشطة',
      forecastTitle: 'توقعات الوصول LSTM',
      forecastSub: 'توقعات الـ 24 ساعة القادمة',
      aiCopilot: 'رؤى مساعد الذكاء الاصطناعي',
      unitHealth: 'مصفوفة صحة الوحدة',
      stats: {
        waiting: 'المرضى المنتظرون',
        critical: 'الحالات الحرجة',
        avgWait: 'متوسط الانتظار (دقيقة)',
        utilization: 'استخدام الموظفين'
      }
    },
    patientDetail: {
      waitTime: 'وقت الانتظار',
      riskScore: 'درجة الخطورة',
      shapTitle: 'تبرير الأولوية (SHAP)',
      vitalsTitle: 'العلامات الحيوية للمريض',
      resourceTitle: 'حالة الموارد',
      assignPhysician: 'تعيين طبيب',
      updatePriority: 'تحديث الأولوية'
    },
    auth: {
      signIn: 'تسجيل الدخول',
      signUp: 'إنشاء حساب',
      signOut: 'خروج',
      email: 'البريد الإلكتروني',
      password: 'كلمة المرور',
      fullName: 'الاسم الكامل',
      role: 'الصفة',
      hospital: 'المستشفى / CHU',
      noAccount: "ليس لديك حساب؟",
      haveAccount: 'لديك حساب بالفعل؟',
      rememberMe: 'تذكرني',
      forgotPassword: 'نسيت كلمة المرور؟',
    },
    saas: {
      pricing: 'الأسعار والخطط',
      billing: 'الفواتير',
      adminPanel: 'لوحة التحكم الكبرى',
      apiDocs: 'توثيق API',
      hospitalSwitcher: 'تغيير المستشفى',
      upgradePlan: 'ترقية الخطة',
    },
  },
  dar: {
    title: 'Hayat',
    tagline: 'سيستيم الترياج الذكي للسبيطارات فالمغرب',
    hero_title: 'Hayat',
    hero_subtitle: 'الذكاء لي كيعتق الروح. كينقص النوبة ب 40% ويعرف الحالات الوعرة دغيا.',
    get_started: 'جرب السيستيم',
    learn_more: 'كيفاش خدام؟',
    intake: 'دخل المريض',
    queue: 'النوبة دابا',
    analytics: 'توقعات ذكية',
    patient_name: 'السمية',
    age: 'العمر',
    vitals: 'العلامات الحيوية',
    hr: 'الدقات',
    bp: 'طونسيو',
    spo2: 'الأوكسجين',
    temp: 'السخانة',
    symptoms: 'الأعراض',
    submit: 'حلل الحالة',
    waiting: 'المرضى دابا',
    priority_p1: 'P1 - دابا دابا',
    priority_p2: 'P2 - مستعجل بزاف',
    priority_p3: 'P3 - مستعجل',
    priority_p4: 'P4 - عادي',
    priority_p5: 'P5 - ماشي مستعجل',
    explanation: 'علاش هاد النتيجة',
    impact_title: 'شنو تبدل؟',
    wait_time_reduction: '40% نقص النوبة',
    critical_detection: '98% كنعرفو الحالات',
    burnout_reduction: '30% راحة للطبة',
    data_driven_title: 'مدرب على بزاف ديال الداتا',
    data_driven_desc: 'النماذج ديالنا كتحلل الداتا باش تعرف كل مريض شنو محتاج.',
    dashboard: {
      header: 'لوحة العمليات الطبية',
      subHeader: 'مراقبة الطوارئ دقيقة بدقيقة • تجربة CHU المغربي',
      admission: 'تسجيل مريض',
      activeMatrix: 'جدول الترياج دابا',
      forecastTitle: 'توقعات الوصول LSTM',
      forecastSub: 'توقعات ديال 24 ساعة الجاية',
      aiCopilot: 'نصائح الذكاء الاصطناعي',
      unitHealth: 'حالة السبيطار دابا',
      stats: {
        waiting: 'المرضى لي كيتسناو',
        critical: 'حالات واعرة',
        avgWait: 'وقت الانتظار (دقيقة)',
        utilization: 'خدمة الموظفين'
      }
    },
    patientDetail: {
      waitTime: 'وقت التسناية',
      riskScore: 'نسبة الخطر',
      shapTitle: 'علاش هاد الأولوية (SHAP)',
      vitalsTitle: 'العلامات الحيوية ديال المريض',
      resourceTitle: 'حالة الموارد',
      assignPhysician: 'عطي الطبيب',
      updatePriority: 'بدل الأولوية'
    },
    auth: {
      signIn: 'دخل للحساب',
      signUp: 'قاد حساب جديد',
      signOut: 'خرج',
      email: 'الإيميل',
      password: 'الكلمة السرية',
      fullName: 'السمية والكنية',
      role: 'الخدمة ديالك',
      hospital: 'السبيطار',
      noAccount: "ماعندكش حساب؟",
      haveAccount: 'فايت مقاد حساب؟',
      rememberMe: 'عقل عليا',
      forgotPassword: 'نسيتي الكلمة السرية؟',
    },
    saas: {
      pricing: 'الأثمنة والاشتراكات',
      billing: 'الخلاص',
      adminPanel: 'طابلو ديال لادمين',
      apiDocs: 'كيفاش تخدم بـ API',
      hospitalSwitcher: 'بدل السبيطار',
      upgradePlan: 'طلع الاشتراك',
    },
  },
  tzm: {
    title: 'Hayat',
    tagline: 'ⴰⵏⴳⵔⴰⵡ ⵏ ⵓⵙⵡⵓⴷⴷⵓ ⵏ ⵜⵓⴷⵔⵜ ⴳ ⵍⵎⵖⵔⵉⴱ',
    hero_title: 'Hayat',
    hero_subtitle: 'ⵜⵓⴷⵔⵜ ⵜⴰⵎⵣⵡⴰⵔⵓⵜ. ⴰⵙⴷⵔⵓⵙ ⵏ ⵜⴳⴰⵍⴰ ⵙ 40%.',
    get_started: 'ⵜⴰⴼⵉⵍⵜ ⵏ ⵓⵙⵡⵓⴷⴷⵓ',
    learn_more: 'ⵎⴰⵎⴽ ⵉⵙⵡⵓⵔⵉ?',
    intake: 'ⴰⵙⵙⴽⵛⵎ',
    queue: 'ⵜⴰⴳⴰⵍⴰ',
    analytics: 'ⵜⵉⴳⴳⵉⵜⵉⵏ',
    patient_name: 'ⵉⵙⵎ',
    age: 'ⴰⵡⵜⴰⵢ',
    vitals: 'ⵜⵉⵎⵉⵜⴰⵔ',
    hr: 'ⴰⵏⴼⵓⵙ',
    bp: 'ⵜⵓⵏⵙⵢⵓ',
    spo2: 'ⵍⵓⴽⵙⵉⵊⵉⵏ',
    temp: 'ⵜⵉⵔⵖⵉ',
    symptoms: 'ⵜⵉⵎⵉⵜⴰⵔ',
    submit: 'ⵣⵔⴳ',
    waiting: 'ⴳ ⵜⴳⴰⵍⴰ',
    priority_p1: 'P1 - ⴰⵙⵙⵉⴷⵔ',
    priority_p2: 'P2 - ⵜⴰⵙⵙⴰⵙⵜ',
    priority_p3: 'P3 - ⵜⴰⵖⴰⵡⵍⴰ',
    priority_p4: 'P4 - ⴰⵎⵢⴰⵏ',
    priority_p5: 'P5 - ⵓⵔ ⵉⵖⴰⵡⵍ',
    explanation: 'ⴰⵙⴼⵙⵔ',
    impact_title: 'ⴰⴷⵔﻴⵣ',
    wait_time_reduction: '40% ⵏ ⵓⵙⴷⵔⵓⵙ',
    critical_detection: '98% ⵏ ⵜⵉⴷⵜ',
    burnout_reduction: '30% ⵏ ⵜⵉⴳⴳⵉⵜ',
    data_driven_title: 'ⵜⴰⴼⵉⵍⵜ ⵏ ⵜⵉⴳⴳⵉⵜⵉⵏ',
    data_driven_desc: 'ⴰⵎⵉⵏⵉⴳ ⵏⵏⵖ ⴰⵔ ⵉⵙⵙⵎⵔⴰⵙ ⵜⵉⴳⴳⵉⵜⵉⵏ ⵏ ⵓⵎⵓⴹⵉⵏ.',
    dashboard: {
      header: 'ⵜⴰⴼⵍⵡⵉⵜ ⵏ ⵜⵉⴳⴳⵉⵜⵉⵏ',
      subHeader: 'ⴰⵙⵡⵓⴷⴷⵓ ⵏ ⵜⵓⴷⵔⵜ ⴳ ⵍⵎⵖⵔⵉⴱ • CHU',
      admission: 'ⴰⵙⵙⴽⵛⵎ',
      activeMatrix: 'ⵜⴰⴳⴰⵍⴰ ⵏ ⵜⵓⴷⵔⵜ',
      forecastTitle: 'LSTM Forecast',
      forecastSub: '24 ⵜⵉⵙⵔⴰⴳⵉⵏ',
      aiCopilot: 'AI Copilot',
      unitHealth: 'ⵜⴰⴼⵍⵡⵉⵜ ⵏ ⵜⵓⴷⵔⵜ',
      stats: {
        waiting: 'ⵉⵎⵓⴹⴰⵏ',
        critical: 'ⵜⴰⵙⵙⴰⵙⵜ',
        avgWait: 'ⵜⵉⵣⵉ',
        utilization: 'ⵜⵉⴳⴳⵉⵜ'
      }
    },
    patientDetail: {
      waitTime: 'ⵜⵉⵣⵉ',
      riskScore: 'ⵜⴰⵙⵙⴰⵙⵜ',
      shapTitle: 'SHAP Justification',
      vitalsTitle: 'ⵜⵉⵎⵉⵜⴰⵔ ⵏ ⵓⵎⵓⴹⵉⵏ',
      resourceTitle: 'Resource Status',
      assignPhysician: 'ⴰⵙⵙⴽⵛⵎ',
      updatePriority: 'ⴱⴷⴷⴻⵍ'
    },
    auth: {
      signIn: 'ⴰⴽⵛⵛⵓّم',
      signUp: 'ⴰⵣⵎⵎⴻⵎ',
      signOut: 'ⴰⴼⵓⵖ',
      email: 'ⵉⵎⴰⵢⵍ',
      password: 'ⵜⴰⴳⵓⵔِي ⵏ ⵓⵣⵔⴰⵢ',
      fullName: 'ⵉⵙⵎ ⴰⵎⵢⴰⵏ',
      role: 'ⵜⴰⵙⵎⵉⴳⵍⵜ',
      hospital: 'ⴰⵙⴳⵏⴰⴼ',
      noAccount: "ⵓⵔ ⵖⵓⵔⴽ ⴰⵎⵉⴹⴰⵏ؟",
      haveAccount: 'ⵖⵓⵔⴽ ⴰⵎⵉⴹⴰَن؟',
      rememberMe: 'ⴽⵜⵉⵢⵉ',
      forgotPassword: 'ⵜⵜⵓⵖ ⵜⴰⴳⵓⵔِي ⵏ ⵓⵣⵔⴰⵢ؟',
    },
    saas: {
      pricing: 'ⵜⵉⴳⴳⵉⵜⵉⵏ',
      billing: 'ⴰⴼⵔⵓ',
      adminPanel: 'ⵜⴰⴼⵍⵡⵉⵜ ⵏ ⵓⵙⵡⵓⴷⴷⵓ',
      apiDocs: 'API',
      hospitalSwitcher: 'ⴱⴷⴷⴻⵍ ⴰⵙⴳⵏⴰⴼ',
      upgradePlan: 'ⵙⵙⵉⴳⵍ ⵜⴰⵙⵎⵉⴳⵍⵜ',
    },
  }
};
